server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courier_tracking?useSSL=false&serverTimezone=UTC
    username: ${prop.spring.dataSources.couriertracking.username}
    password: ${prop.spring.dataSources.couriertracking.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
